### ISSUE TITLE
At the bottom of this awesome lab's readme...

### ISSUE THREAD

**Issue by garettarrowood** [learn-co-curriculum/sql-book-tables#1]
Under For practice:

The 1) reads "create a new database called artists.sql."   But I thought databases had the db extension.  Is this wrong or just counterintuitive ?  Please correct me is I'm wrong.

ALSO - At the very bottom of the readme right above RESOURCES.  The number before "SQLite actually calls its system for etc..." is another number 1.  When I click on the edit tab (which just appeared on this lab for the first time since I've been working on Learn), that number displays correctly as a two. Not sure why it appears wrong on the site...

**Comment by AnnJohn** [comment]
Iceboxing for now
